CREATE TABLE `eq_master` (
	`EQ_SEQ` INT(11) NOT NULL COMMENT '장비번호',
	`EQ_NAME` VARCHAR(200) NULL DEFAULT NULL COMMENT '장비명' COLLATE 'euckr_korean_ci',
	`EQ_TYPE` VARCHAR(10) NULL DEFAULT NULL COMMENT '장비타입' COLLATE 'euckr_korean_ci',
	`EQ_INPUT_DATE` DATETIME NULL DEFAULT NULL COMMENT '도입일자',
	`EQ_USER` VARCHAR(50) NULL DEFAULT NULL COMMENT '장비사용자' COLLATE 'euckr_korean_ci',
	`EQ_STRESS_NUM` INT(3) NULL DEFAULT NULL COMMENT '장비스트레스지수',
	`EQ_DISUSE` DATETIME NULL DEFAULT NULL COMMENT '장비폐기일자',
	`REG_DATE` DATETIME NULL DEFAULT NULL COMMENT '등록일자',
	`REG_USER` VARCHAR(50) NULL DEFAULT NULL COMMENT '등록자' COLLATE 'euckr_korean_ci'
)
COMMENT='장비 마스터 테이블'
COLLATE='armscii8_bin'
ENGINE=InnoDB
;